apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: directus
spec:
  destination:
    name: ''
    namespace: directus
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://github.com/getupcloud/helm-charts'
    targetRevision: 0.0.8
    chart: basic-app
  helm:
    values: |-
      image:
        repository: directus/directus:latest
      containerPort: 8055
      env:
        - name: ADMIN_EMAIL
          value: angela@getupcloud.com
        - name: ADMIN_PASSWORD
          value: admin
        - name: CACHE_ENABLED
          value: "true"
        - name: CACHE_STORE
          value: redis
        - name: DB_CLIENT
          value: mysql
        - name: DB_DATABASE
          value: directus
        - name: DB_HOST
          value: mariadb.mariadb.svc.cluster.local
        - name: DB_PASSWORD
          value: directus
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: directus
        - name: KEY
          value: 255d861b-5ea1-5996-9aa3-922530ec40b1
        - name: REDIS
          value: redis-master.redis.svc.cluster.local
        - name: SECRET
          value: 6116487b-cda1-52c2-b5b5-c8022c45e263      
destination:
  server: 'https://kubernetes.default.svc'
  namespace: directus
syncPolicy:
  automated: {}
  syncOptions:
    - CreateNamespace=true